AB#721 add documentation
edgelesssys/ego.dev pull request #5
Opened 2021-04-22 08:48 UTC by katexochen

- [ ] Add changelog 
- [ ] Collect FAQ
- [ ] Maybe add some insides of EGo and SGX to the SGX page.

2021-04-23 08:42 UTC, thomasten requested changes

2021-04-23 08:42 UTC, thomasten commented on content/docs/tasks/debugging.md
> +EGo executables can be debugged inside as well as outside of enclaves. Depending on the task, you may prefere the on or the other.
```suggestion
EGo executables can be debugged inside as well as outside of enclaves. Depending on the task, you may prefer the one or the other.
```

2021-04-23 08:42 UTC, thomasten commented on content/docs/knowledge/config.md
> +            "fromHost": true
```suggestion
            "fromHost": true
        },
        {
            "name": "PWD",
            "value": "/data"
```
apply change from latest master

2021-04-23 08:42 UTC, thomasten commented on themes/ego/layouts/partials/header.html
> +          <a class="nav-link {{ if eq .Title " Docs" }}active{{ end }}" href="/docs/knowledge/command/">Docs</a>
should we have an introduction page?

2021-04-23 08:42 UTC, thomasten commented on content/docs/tasks/build.md
> +# Build an app with EGo
We should place a prominent link to https://pkg.go.dev/github.com/edgelesssys/ego somewhere. Maybe on this page.

2021-04-26 10:16 UTC, katexochen commented on themes/ego/layouts/partials/header.html
> +          <a class="nav-link {{ if eq .Title " Docs" }}active{{ end }}" href="/docs/knowledge/command/">Docs</a>
In my opinion, the main page is a great introduction page. It lists EGo's features, why you should use EGo and a really quick introduction on how it works. Or do you miss something on the main page, an introduction page could add?

2021-04-26 16:06 UTC, thomasten commented on themes/ego/layouts/partials/header.html
> +          <a class="nav-link {{ if eq .Title " Docs" }}active{{ end }}" href="/docs/knowledge/command/">Docs</a>
Not sure. The command page just seemed a bit of an odd entry to the docs to me. But yes, might be redundant.

2021-04-28 06:24 UTC, katexochen commented on content/docs/tasks/build.md
> +# Build an app with EGo
Maybe we could add a site with some main API functions/features? Or just an overview over the packages we expose and their purpose?

2021-04-28 06:43 UTC, katexochen commented on themes/ego/layouts/partials/header.html
> +          <a class="nav-link {{ if eq .Title " Docs" }}active{{ end }}" href="/docs/knowledge/command/">Docs</a>
I think people who are new to EGo will more likely press the "Get started" button an land on docs/getting-started/install, I've added a welcoming message to that page. People who just want to look up something should be fine with the command page, shouldn't they?

2021-04-28 14:16 UTC, thomasten commented on content/docs/tasks/build.md
> +# Build an app with EGo
I'm not sure. Maybe something brief, but should not be too redundant to the godoc.
We should probably also improve our godocs:
* We should have a root doc.go with a short overview text like
  * https://github.com/stretchr/testify/blob/master/doc.go
  * https://pkg.go.dev/github.com/stretchr/testify
* maybe more detailed package doc comments for the subpackages

2021-04-29 07:27 UTC, katexochen commented on content/docs/tasks/build.md
> +# Build an app with EGo
I think the easiest way then is to just directly link to the godocs. I've manipulated the `docs-sidebare.html` so that a markdown file in the docs folder can represent an external resource and added the` api.md` as reference to the godocs pages. Are you okay with the title "API Reference"? I've added a separate ticket for the godocs improvements.

2021-04-29 07:34 UTC, thomasten commented on content/docs/tasks/build.md
> +# Build an app with EGo
yes, seems like a good approach

2021-04-29 14:39 UTC, katexochen commented
Should we also link https://github.com/edgelesssys/ego/releases as external site with the title "change log"? Would reduce redundancy...

2021-04-29 16:15 UTC, thomasten commented
I'd like that. But I'm interested in other opinions. Look & feel is of course inferior. The ideal way would probably be to autogenerate it from a single source (which could be the releases page). But it's probably not worth the effort yet.

2021-04-30 16:10 UTC, flxflx commented on themes/ego/layouts/partials/header.html
> +          <a class="nav-link {{ if eq .Title " Docs" }}active{{ end }}" href="/docs/knowledge/command/">Docs</a>
I created an introduction page

2021-04-30 16:12 UTC, merged